### ISSUE TITLE
[Question] 重复元素

### ISSUE THREAD

**Issue by QIN2DIM** [HandsomeWalker/utools-plugin-free-game#2]
## 描述

- 感谢开发者带来如此有趣的项目，给我提供了不少灵感。
- 我在 utools store 中安装了这个插件，并在使用中发现了「重复元素」的问题，详细情况如截图所示。
- 我看了下项目源码，尝试复现清洗数据，发现 `"https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=zh-CN"` 这个接口传回的数据具有误导性，按照代码本身的逻辑编排，[《Insurmountable》](https://store.epicgames.com/zh-CN/p/insurmountable-b02c31) 这个游戏会出现在<即将推出>的数组中。

### Utools plugin
![image](https://user-images.githubusercontent.com/62018067/163678084-61a752d5-acdd-4fc4-addd-e1f5abd48fbf.png)

### Epicgames Store
![image](https://user-images.githubusercontent.com/62018067/163678102-f8afb75a-f0e8-409a-a88c-b0cb4346641e.png)

**Comment by HandsomeWalker** [comment]
感谢issue，不好意思，才看到😂
确实存在这个问题，我在开发插件的时候就发现过这个问题，当前是通过**promotionalOffers**和**upcomingPromotionalOffers**这两个字段来判断当前免费和即将免费的游戏，源码中直接是通过判断数组有无元素，看起来在大部分情况下是OK的，比如本周的免费游戏就是OK的。
猜测可以继续向下找到**endDate**字段来多做一层判断，或者直接对比两数组去重（不能保证正确😂）
